version: '3.8'

services:
  mysql:
    container_name: trabalho-bd
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'trabalhobd'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - trabalho-bd:/var/lib/mysql

volumes:
  trabalho-bd: